
CREATE TABLE meeting_role_info (
       meeting_id BIGINT PRIMARY KEY COMMENT '会议号',
       tm CHAR(3) NOT NULL COMMENT '总主持(会员ID)',
       ge CHAR(3) NOT NULL COMMENT '总点评(会员ID)',
       timer VARCHAR(100) COMMENT '时间官',
       grammarian VARCHAR(100) COMMENT '语法官',
       ah_counter VARCHAR(100) COMMENT '哼哈官',
       ttm VARCHAR(100) COMMENT '即兴主持人',
       tte VARCHAR(100) COMMENT '即兴点评',
       pre_speaker1 CHAR(3) COMMENT '备稿演讲者1(会员ID)',
       ie1 CHAR(3) COMMENT '备稿点评1(会员ID)',
       pre_speaker2 CHAR(3) COMMENT '备稿演讲者2(会员ID)',
       ie2 CHAR(3) COMMENT '备稿点评2(会员ID)',
       pre_speaker3 CHAR(3) COMMENT '备稿演讲者3(会员ID)',
       ie3 CHAR(3) COMMENT '备稿点评3(会员ID)',
       pre_speaker4 CHAR(3) COMMENT '备稿演讲者4(会员ID)',
       ie4 CHAR(3) COMMENT '备稿点评4(会员ID)',
       pre_speaker5 CHAR(3) COMMENT '备稿演讲者5(会员ID)',
       ie5 CHAR(3) COMMENT '备稿点评5(会员ID)',
       pre_speaker6 CHAR(3) COMMENT '备稿演讲者6(会员ID)',
       ie6 CHAR(3) COMMENT '备稿点评6(会员ID)',
       posi_debater1 CHAR(3) COMMENT '正方辩手1(会员ID)',
       posi_debater2 CHAR(3) COMMENT '正方辩手2(会员ID)',
       posi_debater3 CHAR(3) COMMENT '正方辩手3(会员ID)',
       nega_debater1 CHAR(3) COMMENT '反方辩手1(会员ID)',
       nega_debater2 CHAR(3) COMMENT '反方辩手2(会员ID)',
       nega_debater3 CHAR(3) COMMENT '反方辩手3(会员ID)',
       deb_evaluator CHAR(3) COMMENT '3V3点评(会员ID)',
       create_by CHAR(3) COMMENT '创建人ID',
       create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
       update_by CHAR(3) COMMENT '修改人ID',
       update_time DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT='会议角色表';